// Generated by tools/generate_assets.py — do not edit by hand.
//
// Exact loop length in frames at 22.05 kHz, per ambience. The app
// trims the decoded AAC to this before scheduling it as a looping
// buffer: the encoder's priming frames would otherwise tick at every
// repeat. Same contract as MusicTrack.loopFrames, same reason.

import Foundation

extension Ambience {
    /// Exact loop length in frames, or nil for `.off`.
    var loopFrames: Int? {
        switch self {
        case .off: nil
        case .cafe: 308700
        case .cicadas: 264600
        case .creek: 529200
        case .crickets: 308700
        case .drizzle: 264600
        case .emberslate: 396900
        case .fireplace: 264600
        case .forest: 308700
        case .library: 441000
        case .nighttrain: 396900
        case .ocean: 617400
        case .purr: 176400
        case .rain: 264600
        case .raintent: 308700
        case .snowhush: 529200
        case .storm: 441000
        case .temple: 529200
        case .wind: 529200
        }
    }
}
