import CoreGraphics

// Generated by tools/generate_accessories.py. Do not edit by hand.
//
// Where an accessory attaches, per buddy frame, measured off the rendered
// sprite rather than typed. Coordinates are in the drawing grid's own units
// (40 x 40), which `Accessory` converts to fractions of whatever size the
// sprite is finally drawn at.
//
// A frame with no row here simply wears nothing — `BuddyFrames`' nil-fallback
// rule, extended to overlays. That is the correct behaviour for a pose whose
// head the measurer could not find, and it is why a missing entry is a
// shrug rather than a crash.
enum BuddyAnchors {

    struct Anchors {
        /// The crown: where the bottom edge of a hat sits.
        let head: CGPoint
        /// How wide the head is, so a hat can be scaled to it.
        let headWidth: CGFloat
        /// The collar line: where the centre of a neck piece sits.
        let neck: CGPoint
        let neckWidth: CGFloat
        /// The last row the animal occupies, for anything that needs to know
        /// where the body stops rather than where the head is.
        let bottom: CGFloat
    }

    /// The grid every coordinate above is measured on.
    static let canvas: CGFloat = 40

    static func anchors(for asset: String) -> Anchors? { table[asset] }

    static let table: [String: Anchors] = [
        "buddy_bunny_asleep": Anchors(
            head: CGPoint(x: 22.5, y: 9),
            headWidth: 30,
            neck: CGPoint(x: 20.0, y: 28),
            neckWidth: 30,
            bottom: 37),
        "buddy_bunny_asleep_breathe": Anchors(
            head: CGPoint(x: 22.5, y: 10),
            headWidth: 30,
            neck: CGPoint(x: 20.0, y: 28),
            neckWidth: 30,
            bottom: 37),
        "buddy_bunny_awake": Anchors(
            head: CGPoint(x: 20.0, y: 6),
            headWidth: 19,
            neck: CGPoint(x: 21.5, y: 28),
            neckWidth: 19,
            bottom: 38),
        "buddy_bunny_awake_blink": Anchors(
            head: CGPoint(x: 20.0, y: 6),
            headWidth: 19,
            neck: CGPoint(x: 21.5, y: 28),
            neckWidth: 19,
            bottom: 38),
        "buddy_bunny_happy_0": Anchors(
            head: CGPoint(x: 20.0, y: 6),
            headWidth: 19,
            neck: CGPoint(x: 21.5, y: 28),
            neckWidth: 19,
            bottom: 38),
        "buddy_bunny_happy_1": Anchors(
            head: CGPoint(x: 20.0, y: 4),
            headWidth: 19,
            neck: CGPoint(x: 21.5, y: 26),
            neckWidth: 19,
            bottom: 36),
        "buddy_bunny_look_l": Anchors(
            head: CGPoint(x: 20.0, y: 6),
            headWidth: 19,
            neck: CGPoint(x: 21.5, y: 28),
            neckWidth: 19,
            bottom: 38),
        "buddy_bunny_look_r": Anchors(
            head: CGPoint(x: 20.0, y: 6),
            headWidth: 19,
            neck: CGPoint(x: 21.5, y: 28),
            neckWidth: 19,
            bottom: 38),
        "buddy_bunny_wake": Anchors(
            head: CGPoint(x: 22.5, y: 9),
            headWidth: 30,
            neck: CGPoint(x: 20.0, y: 28),
            neckWidth: 30,
            bottom: 37),
        "buddy_capybara_asleep": Anchors(
            head: CGPoint(x: 18.0, y: 16),
            headWidth: 29,
            neck: CGPoint(x: 20.0, y: 30),
            neckWidth: 29,
            bottom: 37),
        "buddy_capybara_asleep_breathe": Anchors(
            head: CGPoint(x: 18.0, y: 17),
            headWidth: 29,
            neck: CGPoint(x: 20.0, y: 31),
            neckWidth: 29,
            bottom: 37),
        "buddy_capybara_awake": Anchors(
            head: CGPoint(x: 20.0, y: 7),
            headWidth: 27,
            neck: CGPoint(x: 20.0, y: 28),
            neckWidth: 27,
            bottom: 38),
        "buddy_capybara_awake_blink": Anchors(
            head: CGPoint(x: 20.0, y: 7),
            headWidth: 27,
            neck: CGPoint(x: 20.0, y: 28),
            neckWidth: 27,
            bottom: 38),
        "buddy_capybara_happy_0": Anchors(
            head: CGPoint(x: 20.0, y: 7),
            headWidth: 27,
            neck: CGPoint(x: 20.0, y: 28),
            neckWidth: 27,
            bottom: 38),
        "buddy_capybara_happy_1": Anchors(
            head: CGPoint(x: 20.0, y: 5),
            headWidth: 27,
            neck: CGPoint(x: 20.0, y: 26),
            neckWidth: 27,
            bottom: 36),
        "buddy_capybara_look_l": Anchors(
            head: CGPoint(x: 20.0, y: 7),
            headWidth: 27,
            neck: CGPoint(x: 20.0, y: 28),
            neckWidth: 27,
            bottom: 38),
        "buddy_capybara_look_r": Anchors(
            head: CGPoint(x: 20.0, y: 7),
            headWidth: 27,
            neck: CGPoint(x: 20.0, y: 28),
            neckWidth: 27,
            bottom: 38),
        "buddy_capybara_soak": Anchors(
            head: CGPoint(x: 20.0, y: 11),
            headWidth: 23,
            neck: CGPoint(x: 20.0, y: 30),
            neckWidth: 23,
            bottom: 39),
        "buddy_capybara_wake": Anchors(
            head: CGPoint(x: 18.0, y: 16),
            headWidth: 29,
            neck: CGPoint(x: 20.0, y: 30),
            neckWidth: 29,
            bottom: 37),
        "buddy_cat_asleep": Anchors(
            head: CGPoint(x: 17.0, y: 14),
            headWidth: 23,
            neck: CGPoint(x: 20.0, y: 31),
            neckWidth: 23,
            bottom: 39),
        "buddy_cat_asleep_breathe": Anchors(
            head: CGPoint(x: 17.0, y: 15),
            headWidth: 23,
            neck: CGPoint(x: 20.0, y: 31),
            neckWidth: 23,
            bottom: 39),
        "buddy_cat_awake": Anchors(
            head: CGPoint(x: 20.0, y: 6),
            headWidth: 27,
            neck: CGPoint(x: 23.0, y: 28),
            neckWidth: 27,
            bottom: 38),
        "buddy_cat_awake_blink": Anchors(
            head: CGPoint(x: 20.0, y: 6),
            headWidth: 27,
            neck: CGPoint(x: 23.0, y: 28),
            neckWidth: 27,
            bottom: 38),
        "buddy_cat_happy_0": Anchors(
            head: CGPoint(x: 20.0, y: 6),
            headWidth: 27,
            neck: CGPoint(x: 23.0, y: 28),
            neckWidth: 27,
            bottom: 38),
        "buddy_cat_happy_1": Anchors(
            head: CGPoint(x: 20.0, y: 4),
            headWidth: 27,
            neck: CGPoint(x: 23.0, y: 26),
            neckWidth: 27,
            bottom: 36),
        "buddy_cat_look_l": Anchors(
            head: CGPoint(x: 20.0, y: 6),
            headWidth: 27,
            neck: CGPoint(x: 23.0, y: 28),
            neckWidth: 27,
            bottom: 38),
        "buddy_cat_look_r": Anchors(
            head: CGPoint(x: 20.0, y: 6),
            headWidth: 27,
            neck: CGPoint(x: 23.0, y: 28),
            neckWidth: 27,
            bottom: 38),
        "buddy_cat_stretch": Anchors(
            head: CGPoint(x: 30.0, y: 16),
            headWidth: 15,
            neck: CGPoint(x: 19.5, y: 31),
            neckWidth: 15,
            bottom: 38),
        "buddy_cat_wake": Anchors(
            head: CGPoint(x: 17.0, y: 14),
            headWidth: 23,
            neck: CGPoint(x: 20.0, y: 31),
            neckWidth: 23,
            bottom: 39),
        "buddy_dog_asleep": Anchors(
            head: CGPoint(x: 16.5, y: 18),
            headWidth: 34,
            neck: CGPoint(x: 17.5, y: 32),
            neckWidth: 32,
            bottom: 39),
        "buddy_dog_asleep_breathe": Anchors(
            head: CGPoint(x: 16.5, y: 19),
            headWidth: 34,
            neck: CGPoint(x: 18.0, y: 33),
            neckWidth: 31,
            bottom: 39),
        "buddy_dog_awake": Anchors(
            head: CGPoint(x: 20.0, y: 8),
            headWidth: 35,
            neck: CGPoint(x: 23.0, y: 28),
            neckWidth: 31,
            bottom: 38),
        "buddy_dog_awake_blink": Anchors(
            head: CGPoint(x: 20.0, y: 8),
            headWidth: 35,
            neck: CGPoint(x: 23.0, y: 28),
            neckWidth: 31,
            bottom: 38),
        "buddy_dog_happy_0": Anchors(
            head: CGPoint(x: 20.0, y: 8),
            headWidth: 35,
            neck: CGPoint(x: 23.0, y: 28),
            neckWidth: 31,
            bottom: 38),
        "buddy_dog_happy_1": Anchors(
            head: CGPoint(x: 20.0, y: 6),
            headWidth: 35,
            neck: CGPoint(x: 23.0, y: 26),
            neckWidth: 31,
            bottom: 36),
        "buddy_dog_look_l": Anchors(
            head: CGPoint(x: 20.0, y: 8),
            headWidth: 35,
            neck: CGPoint(x: 23.0, y: 28),
            neckWidth: 31,
            bottom: 38),
        "buddy_dog_look_r": Anchors(
            head: CGPoint(x: 20.0, y: 8),
            headWidth: 35,
            neck: CGPoint(x: 23.0, y: 28),
            neckWidth: 31,
            bottom: 38),
        "buddy_dog_stretch": Anchors(
            head: CGPoint(x: 20.0, y: 21),
            headWidth: 37,
            neck: CGPoint(x: 17.0, y: 33),
            neckWidth: 33,
            bottom: 38),
        "buddy_dog_wake": Anchors(
            head: CGPoint(x: 16.5, y: 18),
            headWidth: 34,
            neck: CGPoint(x: 17.5, y: 32),
            neckWidth: 32,
            bottom: 39),
        "buddy_fox_asleep": Anchors(
            head: CGPoint(x: 17.0, y: 14),
            headWidth: 23,
            neck: CGPoint(x: 20.5, y: 31),
            neckWidth: 23,
            bottom: 39),
        "buddy_fox_asleep_breathe": Anchors(
            head: CGPoint(x: 17.0, y: 15),
            headWidth: 23,
            neck: CGPoint(x: 20.5, y: 31),
            neckWidth: 23,
            bottom: 39),
        "buddy_fox_awake": Anchors(
            head: CGPoint(x: 20.0, y: 7),
            headWidth: 27,
            neck: CGPoint(x: 23.5, y: 28),
            neckWidth: 27,
            bottom: 38),
        "buddy_fox_awake_blink": Anchors(
            head: CGPoint(x: 20.0, y: 7),
            headWidth: 27,
            neck: CGPoint(x: 23.5, y: 28),
            neckWidth: 27,
            bottom: 38),
        "buddy_fox_happy_0": Anchors(
            head: CGPoint(x: 20.0, y: 7),
            headWidth: 27,
            neck: CGPoint(x: 23.5, y: 28),
            neckWidth: 27,
            bottom: 38),
        "buddy_fox_happy_1": Anchors(
            head: CGPoint(x: 20.0, y: 5),
            headWidth: 27,
            neck: CGPoint(x: 23.5, y: 26),
            neckWidth: 27,
            bottom: 36),
        "buddy_fox_look_l": Anchors(
            head: CGPoint(x: 20.0, y: 7),
            headWidth: 27,
            neck: CGPoint(x: 23.5, y: 28),
            neckWidth: 27,
            bottom: 38),
        "buddy_fox_look_r": Anchors(
            head: CGPoint(x: 20.0, y: 7),
            headWidth: 27,
            neck: CGPoint(x: 23.5, y: 28),
            neckWidth: 27,
            bottom: 38),
        "buddy_fox_wake": Anchors(
            head: CGPoint(x: 17.0, y: 14),
            headWidth: 23,
            neck: CGPoint(x: 20.5, y: 31),
            neckWidth: 23,
            bottom: 39),
        "buddy_hamster_asleep": Anchors(
            head: CGPoint(x: 18.5, y: 16),
            headWidth: 26,
            neck: CGPoint(x: 20.0, y: 31),
            neckWidth: 26,
            bottom: 38),
        "buddy_hamster_asleep_breathe": Anchors(
            head: CGPoint(x: 17.5, y: 14),
            headWidth: 24,
            neck: CGPoint(x: 20.0, y: 30),
            neckWidth: 24,
            bottom: 38),
        "buddy_hamster_awake": Anchors(
            head: CGPoint(x: 20.0, y: 13),
            headWidth: 27,
            neck: CGPoint(x: 20.0, y: 30),
            neckWidth: 27,
            bottom: 38),
        "buddy_hamster_awake_blink": Anchors(
            head: CGPoint(x: 20.0, y: 13),
            headWidth: 27,
            neck: CGPoint(x: 20.0, y: 30),
            neckWidth: 27,
            bottom: 38),
        "buddy_hamster_happy_0": Anchors(
            head: CGPoint(x: 20.0, y: 13),
            headWidth: 27,
            neck: CGPoint(x: 20.0, y: 30),
            neckWidth: 27,
            bottom: 38),
        "buddy_hamster_happy_1": Anchors(
            head: CGPoint(x: 20.0, y: 11),
            headWidth: 27,
            neck: CGPoint(x: 20.0, y: 28),
            neckWidth: 27,
            bottom: 36),
        "buddy_hamster_look_l": Anchors(
            head: CGPoint(x: 20.0, y: 13),
            headWidth: 27,
            neck: CGPoint(x: 20.0, y: 30),
            neckWidth: 27,
            bottom: 38),
        "buddy_hamster_look_r": Anchors(
            head: CGPoint(x: 20.0, y: 13),
            headWidth: 27,
            neck: CGPoint(x: 20.0, y: 30),
            neckWidth: 27,
            bottom: 38),
        "buddy_hamster_wake": Anchors(
            head: CGPoint(x: 18.5, y: 16),
            headWidth: 26,
            neck: CGPoint(x: 20.0, y: 31),
            neckWidth: 26,
            bottom: 38),
        "buddy_hedgehog_asleep": Anchors(
            head: CGPoint(x: 20.0, y: 12),
            headWidth: 31,
            neck: CGPoint(x: 20.0, y: 30),
            neckWidth: 31,
            bottom: 39),
        "buddy_hedgehog_asleep_breathe": Anchors(
            head: CGPoint(x: 20.0, y: 13),
            headWidth: 31,
            neck: CGPoint(x: 18.5, y: 31),
            neckWidth: 30,
            bottom: 39),
        "buddy_hedgehog_awake": Anchors(
            head: CGPoint(x: 19.5, y: 12),
            headWidth: 32,
            neck: CGPoint(x: 20.0, y: 30),
            neckWidth: 31,
            bottom: 39),
        "buddy_hedgehog_awake_blink": Anchors(
            head: CGPoint(x: 19.5, y: 12),
            headWidth: 32,
            neck: CGPoint(x: 20.0, y: 30),
            neckWidth: 31,
            bottom: 39),
        "buddy_hedgehog_happy_0": Anchors(
            head: CGPoint(x: 19.5, y: 12),
            headWidth: 32,
            neck: CGPoint(x: 20.0, y: 30),
            neckWidth: 31,
            bottom: 39),
        "buddy_hedgehog_happy_1": Anchors(
            head: CGPoint(x: 19.5, y: 10),
            headWidth: 32,
            neck: CGPoint(x: 20.0, y: 28),
            neckWidth: 31,
            bottom: 37),
        "buddy_hedgehog_look_l": Anchors(
            head: CGPoint(x: 19.5, y: 12),
            headWidth: 32,
            neck: CGPoint(x: 20.0, y: 30),
            neckWidth: 31,
            bottom: 39),
        "buddy_hedgehog_look_r": Anchors(
            head: CGPoint(x: 19.5, y: 12),
            headWidth: 32,
            neck: CGPoint(x: 20.0, y: 30),
            neckWidth: 31,
            bottom: 39),
        "buddy_hedgehog_wake": Anchors(
            head: CGPoint(x: 20.0, y: 12),
            headWidth: 31,
            neck: CGPoint(x: 20.0, y: 30),
            neckWidth: 31,
            bottom: 39),
        "buddy_otter_asleep": Anchors(
            head: CGPoint(x: 18.5, y: 15),
            headWidth: 30,
            neck: CGPoint(x: 20.0, y: 31),
            neckWidth: 30,
            bottom: 39),
        "buddy_otter_asleep_breathe": Anchors(
            head: CGPoint(x: 18.5, y: 16),
            headWidth: 30,
            neck: CGPoint(x: 20.5, y: 32),
            neckWidth: 30,
            bottom: 39),
        "buddy_otter_awake": Anchors(
            head: CGPoint(x: 20.0, y: 6),
            headWidth: 25,
            neck: CGPoint(x: 20.0, y: 28),
            neckWidth: 23,
            bottom: 39),
        "buddy_otter_awake_blink": Anchors(
            head: CGPoint(x: 20.0, y: 6),
            headWidth: 25,
            neck: CGPoint(x: 20.0, y: 28),
            neckWidth: 23,
            bottom: 39),
        "buddy_otter_float": Anchors(
            head: CGPoint(x: 20.0, y: 16),
            headWidth: 37,
            neck: CGPoint(x: 19.5, y: 26),
            neckWidth: 34,
            bottom: 31),
        "buddy_otter_happy_0": Anchors(
            head: CGPoint(x: 20.0, y: 6),
            headWidth: 25,
            neck: CGPoint(x: 20.0, y: 28),
            neckWidth: 23,
            bottom: 39),
        "buddy_otter_happy_1": Anchors(
            head: CGPoint(x: 20.0, y: 4),
            headWidth: 25,
            neck: CGPoint(x: 20.0, y: 26),
            neckWidth: 23,
            bottom: 37),
        "buddy_otter_look_l": Anchors(
            head: CGPoint(x: 20.0, y: 6),
            headWidth: 25,
            neck: CGPoint(x: 20.0, y: 28),
            neckWidth: 23,
            bottom: 39),
        "buddy_otter_look_r": Anchors(
            head: CGPoint(x: 20.0, y: 6),
            headWidth: 25,
            neck: CGPoint(x: 20.0, y: 28),
            neckWidth: 23,
            bottom: 39),
        "buddy_otter_wake": Anchors(
            head: CGPoint(x: 18.5, y: 15),
            headWidth: 30,
            neck: CGPoint(x: 20.0, y: 31),
            neckWidth: 30,
            bottom: 39),
        "buddy_owl_asleep": Anchors(
            head: CGPoint(x: 16.0, y: 13),
            headWidth: 23,
            neck: CGPoint(x: 20.0, y: 30),
            neckWidth: 23,
            bottom: 38),
        "buddy_owl_asleep_breathe": Anchors(
            head: CGPoint(x: 16.0, y: 14),
            headWidth: 23,
            neck: CGPoint(x: 20.0, y: 30),
            neckWidth: 23,
            bottom: 38),
        "buddy_owl_awake": Anchors(
            head: CGPoint(x: 20.0, y: 8),
            headWidth: 27,
            neck: CGPoint(x: 20.0, y: 29),
            neckWidth: 27,
            bottom: 39),
        "buddy_owl_awake_blink": Anchors(
            head: CGPoint(x: 20.0, y: 8),
            headWidth: 27,
            neck: CGPoint(x: 20.0, y: 29),
            neckWidth: 27,
            bottom: 39),
        "buddy_owl_happy_0": Anchors(
            head: CGPoint(x: 20.0, y: 8),
            headWidth: 27,
            neck: CGPoint(x: 20.0, y: 29),
            neckWidth: 27,
            bottom: 39),
        "buddy_owl_happy_1": Anchors(
            head: CGPoint(x: 20.0, y: 6),
            headWidth: 27,
            neck: CGPoint(x: 20.0, y: 27),
            neckWidth: 27,
            bottom: 37),
        "buddy_owl_look_l": Anchors(
            head: CGPoint(x: 19.5, y: 8),
            headWidth: 28,
            neck: CGPoint(x: 20.0, y: 29),
            neckWidth: 28,
            bottom: 39),
        "buddy_owl_look_r": Anchors(
            head: CGPoint(x: 20.5, y: 8),
            headWidth: 28,
            neck: CGPoint(x: 20.0, y: 29),
            neckWidth: 28,
            bottom: 39),
        "buddy_owl_wake": Anchors(
            head: CGPoint(x: 16.0, y: 13),
            headWidth: 23,
            neck: CGPoint(x: 20.0, y: 30),
            neckWidth: 23,
            bottom: 38),
        "buddy_owl_watch": Anchors(
            head: CGPoint(x: 20.0, y: 9),
            headWidth: 29,
            neck: CGPoint(x: 20.0, y: 29),
            neckWidth: 29,
            bottom: 39),
        "buddy_penguin_asleep": Anchors(
            head: CGPoint(x: 18.5, y: 16),
            headWidth: 30,
            neck: CGPoint(x: 20.0, y: 31),
            neckWidth: 29,
            bottom: 38),
        "buddy_penguin_asleep_breathe": Anchors(
            head: CGPoint(x: 18.0, y: 17),
            headWidth: 29,
            neck: CGPoint(x: 20.0, y: 31),
            neckWidth: 29,
            bottom: 38),
        "buddy_penguin_awake": Anchors(
            head: CGPoint(x: 20.0, y: 10),
            headWidth: 31,
            neck: CGPoint(x: 20.0, y: 30),
            neckWidth: 31,
            bottom: 39),
        "buddy_penguin_awake_blink": Anchors(
            head: CGPoint(x: 20.0, y: 10),
            headWidth: 31,
            neck: CGPoint(x: 20.0, y: 30),
            neckWidth: 31,
            bottom: 39),
        "buddy_penguin_happy_0": Anchors(
            head: CGPoint(x: 20.0, y: 10),
            headWidth: 31,
            neck: CGPoint(x: 20.0, y: 30),
            neckWidth: 31,
            bottom: 39),
        "buddy_penguin_happy_1": Anchors(
            head: CGPoint(x: 20.0, y: 8),
            headWidth: 31,
            neck: CGPoint(x: 20.0, y: 28),
            neckWidth: 31,
            bottom: 37),
        "buddy_penguin_look_l": Anchors(
            head: CGPoint(x: 20.0, y: 10),
            headWidth: 31,
            neck: CGPoint(x: 20.0, y: 30),
            neckWidth: 31,
            bottom: 39),
        "buddy_penguin_look_r": Anchors(
            head: CGPoint(x: 20.0, y: 10),
            headWidth: 31,
            neck: CGPoint(x: 20.0, y: 30),
            neckWidth: 31,
            bottom: 39),
        "buddy_penguin_slide": Anchors(
            head: CGPoint(x: 21.0, y: 21),
            headWidth: 37,
            neck: CGPoint(x: 21.0, y: 31),
            neckWidth: 33,
            bottom: 36),
        "buddy_penguin_waddle": Anchors(
            head: CGPoint(x: 19.0, y: 10),
            headWidth: 33,
            neck: CGPoint(x: 24.5, y: 30),
            neckWidth: 26,
            bottom: 39),
        "buddy_penguin_wake": Anchors(
            head: CGPoint(x: 18.5, y: 16),
            headWidth: 30,
            neck: CGPoint(x: 20.0, y: 31),
            neckWidth: 29,
            bottom: 38),
        "buddy_redpanda_armsup": Anchors(
            head: CGPoint(x: 20.0, y: 9),
            headWidth: 37,
            neck: CGPoint(x: 20.0, y: 29),
            neckWidth: 19,
            bottom: 39),
        "buddy_redpanda_asleep": Anchors(
            head: CGPoint(x: 17.5, y: 14),
            headWidth: 28,
            neck: CGPoint(x: 20.0, y: 31),
            neckWidth: 28,
            bottom: 39),
        "buddy_redpanda_asleep_breathe": Anchors(
            head: CGPoint(x: 17.0, y: 15),
            headWidth: 27,
            neck: CGPoint(x: 20.0, y: 31),
            neckWidth: 27,
            bottom: 39),
        "buddy_redpanda_awake": Anchors(
            head: CGPoint(x: 20.0, y: 7),
            headWidth: 31,
            neck: CGPoint(x: 23.0, y: 28),
            neckWidth: 31,
            bottom: 38),
        "buddy_redpanda_awake_blink": Anchors(
            head: CGPoint(x: 20.0, y: 7),
            headWidth: 31,
            neck: CGPoint(x: 23.0, y: 28),
            neckWidth: 31,
            bottom: 38),
        "buddy_redpanda_curl": Anchors(
            head: CGPoint(x: 19.0, y: 18),
            headWidth: 29,
            neck: CGPoint(x: 20.0, y: 32),
            neckWidth: 29,
            bottom: 39),
        "buddy_redpanda_happy_0": Anchors(
            head: CGPoint(x: 20.0, y: 7),
            headWidth: 31,
            neck: CGPoint(x: 23.0, y: 28),
            neckWidth: 31,
            bottom: 38),
        "buddy_redpanda_happy_1": Anchors(
            head: CGPoint(x: 20.0, y: 5),
            headWidth: 31,
            neck: CGPoint(x: 23.0, y: 26),
            neckWidth: 31,
            bottom: 36),
        "buddy_redpanda_look_l": Anchors(
            head: CGPoint(x: 20.0, y: 7),
            headWidth: 31,
            neck: CGPoint(x: 23.0, y: 28),
            neckWidth: 31,
            bottom: 38),
        "buddy_redpanda_look_r": Anchors(
            head: CGPoint(x: 20.0, y: 7),
            headWidth: 31,
            neck: CGPoint(x: 23.0, y: 28),
            neckWidth: 31,
            bottom: 38),
        "buddy_redpanda_wake": Anchors(
            head: CGPoint(x: 17.5, y: 14),
            headWidth: 28,
            neck: CGPoint(x: 20.0, y: 31),
            neckWidth: 28,
            bottom: 39),
        "buddy_stray_asleep": Anchors(
            head: CGPoint(x: 17.0, y: 14),
            headWidth: 23,
            neck: CGPoint(x: 20.0, y: 31),
            neckWidth: 23,
            bottom: 39),
        "buddy_stray_asleep_breathe": Anchors(
            head: CGPoint(x: 17.0, y: 15),
            headWidth: 23,
            neck: CGPoint(x: 20.0, y: 31),
            neckWidth: 23,
            bottom: 39),
        "buddy_stray_awake": Anchors(
            head: CGPoint(x: 20.0, y: 6),
            headWidth: 27,
            neck: CGPoint(x: 23.0, y: 28),
            neckWidth: 27,
            bottom: 38),
        "buddy_stray_awake_blink": Anchors(
            head: CGPoint(x: 20.0, y: 6),
            headWidth: 27,
            neck: CGPoint(x: 23.0, y: 28),
            neckWidth: 27,
            bottom: 38),
        "buddy_stray_happy_0": Anchors(
            head: CGPoint(x: 20.0, y: 6),
            headWidth: 27,
            neck: CGPoint(x: 23.0, y: 28),
            neckWidth: 27,
            bottom: 38),
        "buddy_stray_happy_1": Anchors(
            head: CGPoint(x: 20.0, y: 4),
            headWidth: 27,
            neck: CGPoint(x: 23.0, y: 26),
            neckWidth: 27,
            bottom: 36),
        "buddy_stray_look_l": Anchors(
            head: CGPoint(x: 20.0, y: 6),
            headWidth: 27,
            neck: CGPoint(x: 23.0, y: 28),
            neckWidth: 27,
            bottom: 38),
        "buddy_stray_look_r": Anchors(
            head: CGPoint(x: 20.0, y: 6),
            headWidth: 27,
            neck: CGPoint(x: 23.0, y: 28),
            neckWidth: 27,
            bottom: 38),
        "buddy_stray_stretch": Anchors(
            head: CGPoint(x: 30.0, y: 16),
            headWidth: 15,
            neck: CGPoint(x: 19.5, y: 31),
            neckWidth: 15,
            bottom: 38),
        "buddy_stray_wake": Anchors(
            head: CGPoint(x: 17.0, y: 14),
            headWidth: 23,
            neck: CGPoint(x: 20.0, y: 31),
            neckWidth: 23,
            bottom: 39),
    ]
}
