import CoreGraphics
import Foundation

/// The light this world is drawn in, applied to a photograph of yours.
///
/// Not Instagram presets. Every stock here is a grade the app *already uses* on
/// its own art — the four times of day the scenes are exported in, the sepia
/// the field journal presses its sketches in, the tints the seasons wear. A
/// photo of your desk under `dusk` is lit by exactly the arithmetic that lights
/// Whispering Woods at dusk, to the coefficient.
///
/// ### Why there is no LUT file
///
/// `HEARTH_PLAN` asked for Core Image colour cubes generated by a tool. There
/// is nothing to generate: `tools/generate_scenes.py` grades a palette with
/// three numbers — a tint to pull toward, how far to pull, and a brightness
/// multiplier — and that is a per-channel affine transform Core Image can do
/// with `CIColorMatrix` and `CIColorControls` directly. A LUT would be a
/// lossy, hundred-kilobyte copy of six numbers.
///
/// The real win is that it makes the claim *checkable*:
/// `tools/check_film.py` parses `GRADE` out of the scene generator and the
/// sepia coefficients out of the wildlife generator, and fails if this file
/// disagrees with either. The filters cannot drift away from the world's own
/// light, because the world's own light is where they are read from.
enum FilmStock: String, CaseIterable, Identifiable, Codable {
    /// No grade at all. The photograph as taken — always available, always
    /// first, and the one everybody who does not care about this feature uses.
    case asitwas
    case dawn
    case dusk
    case night
    /// The field journal's press. Free, because the Scrapbook's own default
    /// dress-up has to be, and because it is the one that makes a photo look
    /// like it belongs in this app.
    case pressed
    case sakura
    case winter

    var id: String { rawValue }

    var name: String {
        switch self {
        case .asitwas: "As it was"
        case .dawn: "First light"
        case .dusk: "Last light"
        case .night: "After dark"
        case .pressed: "Pressed"
        case .sakura: "Blossom"
        case .winter: "Cold"
        }
    }

    /// The three numbers, exactly as `tools/generate_scenes.py` writes them.
    ///
    /// `tint` is the colour each channel is pulled toward, 0–255. `amount` is
    /// how far. `multiplier` is the brightness afterwards. Change one and
    /// `check_film.py` fails unless the generator changed the same way.
    var grade: (tint: (Double, Double, Double), amount: Double, multiplier: Double) {
        switch self {
        case .asitwas: ((255, 255, 255), 0.00, 1.00)
        case .dawn: ((255, 174, 152), 0.34, 0.94)
        case .dusk: ((255, 142, 108), 0.32, 0.86)
        case .night: ((44, 62, 120), 0.52, 0.68)
        // The journal's sepia is a different shape — it desaturates to
        // luminance first and then tints — so it carries its own arm in
        // `transform` below rather than pretending to be a pull-toward.
        case .pressed: ((0, 0, 0), 0, 1)
        case .sakura: ((255, 208, 224), 0.26, 1.02)
        case .winter: ((196, 220, 255), 0.30, 0.96)
        }
    }

    /// Whether this stock desaturates before tinting. Only the journal's press
    /// does, and it is the one thing about it that makes it read as *pressed*
    /// rather than as a warm filter.
    var desaturates: Bool { self == .pressed }

    /// The sepia coefficients, matching `sepia()` in
    /// `tools/generate_wildlife.py`: grey × scale + offset, per channel.
    static let press: (scale: (Double, Double, Double), offset: (Double, Double, Double)) =
        ((0.62, 0.56, 0.46), (86, 62, 44))

    /// The transform as Core Image wants it: a 4x4-ish colour matrix plus a
    /// saturation, both derived from the grade above rather than typed twice.
    ///
    /// A pull toward a tint by `amount` is `channel * (1 - amount) + target *
    /// amount`, which is a scale and a bias per channel — so it maps onto
    /// `CIColorMatrix`'s vectors exactly. The multiplier folds into the scale.
    var matrix: (scale: (Double, Double, Double), bias: (Double, Double, Double)) {
        if desaturates {
            // Applied after the saturation is taken out, so the "channel" is
            // already luminance and the whole thing is one affine step.
            return (Self.press.scale,
                    (Self.press.offset.0 / 255,
                     Self.press.offset.1 / 255,
                     Self.press.offset.2 / 255))
        }
        let (tint, amount, multiplier) = grade
        let keep = (1 - amount) * multiplier
        return ((keep, keep, keep),
                (tint.0 / 255 * amount * multiplier,
                 tint.1 / 255 * amount * multiplier,
                 tint.2 / 255 * amount * multiplier))
    }

    /// What this does to one colour, 0–1 per channel.
    ///
    /// The app uses `matrix` and Core Image does the work; this exists so the
    /// arithmetic can be stated once, tested against a stored fixture, and
    /// compared with the Python that grades the scenes. If the two ever
    /// disagree the filters have stopped being the world's light.
    func apply(_ colour: (Double, Double, Double)) -> (Double, Double, Double) {
        var (r, g, b) = colour
        if desaturates {
            let grey = 0.299 * r + 0.587 * g + 0.114 * b
            r = grey; g = grey; b = grey
        }
        let (scale, bias) = matrix
        return (min(1, max(0, r * scale.0 + bias.0)),
                min(1, max(0, g * scale.1 + bias.1)),
                min(1, max(0, b * scale.2 + bias.2)))
    }

    // MARK: What is free

    /// The three anybody has without trading: the photograph as taken, the
    /// journal's press, and the light the app is in most of the time.
    ///
    /// Fence 6 — the memory is never the product. Capture is free forever and
    /// so is enough dress-up to make a photo feel like it belongs here; only
    /// the extra stocks join the cart.
    var isFree: Bool {
        switch self {
        case .asitwas, .pressed, .dusk: true
        case .dawn, .night, .sakura, .winter: false
        }
    }

    var catalogItem: CatalogItem? { isFree ? nil : .film(self) }
}
