// Generated by tools/generate_music.py — do not edit by hand.
//
// Loop frames are exact: the app trims the decoded AAC buffer to this
// length before scheduling it as a looping buffer, which is what makes
// playback gapless (the encoder adds priming samples that would
// otherwise tick at every repeat).

import Foundation

/// One track in the Sound Almanac.
struct MusicTrack: Identifiable, Equatable, Hashable {
    let id: String
    let title: String
    let collection: String
    let gate: MusicGate
    let bpm: Int
    /// 1 quiet, 2 steady, 3 brighter — used by radio mode to match the hour.
    let energy: Int
    /// Exact loop length in frames at 22.05 kHz.
    let loopFrames: Int

    var assetName: String { id }
}

enum MusicCatalog {
    static let collections: [MusicCollection] = [
        MusicCollection(id: "chill1", title: "Paws & Chill I", blurb: "The classic study loop.", gate: .free),
        MusicCollection(id: "meadow", title: "Meadow Mornings", blurb: "Gentle, and a little birdsong.", gate: .arrival(.meadow)),
    ]

    static let tracks: [MusicTrack] = [
        MusicTrack(id: "first_light", title: "First Light Loop", collection: "chill1", gate: .free, bpm: 70, energy: 2, loopFrames: 604800),
        MusicTrack(id: "homework_for_two", title: "Homework for Two", collection: "chill1", gate: .free, bpm: 72, energy: 2, loopFrames: 588000),
        MusicTrack(id: "corner_desk", title: "Corner Desk", collection: "chill1", gate: .free, bpm: 68, energy: 2, loopFrames: 622592),
        MusicTrack(id: "sleepy_metronome", title: "Sleepy Metronome", collection: "chill1", gate: .free, bpm: 66, energy: 1, loopFrames: 641456),
        MusicTrack(id: "warm_static", title: "Warm Static", collection: "chill1", gate: .free, bpm: 74, energy: 2, loopFrames: 572112),
        MusicTrack(id: "dew_on_the_fence", title: "Dew on the Fence", collection: "meadow", gate: .arrival(.meadow), bpm: 76, energy: 3, loopFrames: 557056),
        MusicTrack(id: "kettle_song", title: "Kettle Song", collection: "meadow", gate: .arrival(.meadow), bpm: 70, energy: 2, loopFrames: 604800),
        MusicTrack(id: "clover_rows", title: "Clover Rows", collection: "meadow", gate: .arrival(.meadow), bpm: 72, energy: 2, loopFrames: 588000),
        MusicTrack(id: "biscuits_nap", title: "Biscuit's Nap", collection: "meadow", gate: .arrival(.meadow), bpm: 64, energy: 1, loopFrames: 661504),
        MusicTrack(id: "chimney_smoke", title: "Chimney Smoke", collection: "meadow", gate: .arrival(.meadow), bpm: 68, energy: 1, loopFrames: 622592),
    ]

    static func tracks(in collection: String) -> [MusicTrack] {
        tracks.filter { $0.collection == collection }
    }

    static func track(id: String) -> MusicTrack? {
        tracks.first { $0.id == id }
    }

    /// The one everybody starts with.
    static var opener: MusicTrack { tracks[0] }
}
