// Generated by tools/generate_music.py — do not edit by hand.
//
// Loop frames are exact: the app trims the decoded AAC buffer to this
// length before scheduling it as a looping buffer, which is what makes
// playback gapless (the encoder adds priming samples that would
// otherwise tick at every repeat).

import Foundation

/// One track in the Sound Almanac.
struct MusicTrack: Identifiable, Equatable, Hashable {
    let id: String
    let title: String
    let collection: String
    let gate: MusicGate
    let bpm: Int
    /// 1 quiet, 2 steady, 3 brighter — used by radio mode to match the hour.
    let energy: Int
    /// Exact loop length in frames at 22.05 kHz.
    let loopFrames: Int

    var assetName: String { id }
}

enum MusicCatalog {
    static let collections: [MusicCollection] = [
        MusicCollection(id: "chill1", title: "Paws & Chill I", blurb: "The classic study loop.", gate: .free),
        MusicCollection(id: "meadow", title: "Meadow Mornings", blurb: "Gentle, and a little birdsong.", gate: .arrival(.meadow)),
        MusicCollection(id: "woods", title: "Under the Pines", blurb: "Minor keys, wind and water.", gate: .arrival(.woods)),
        MusicCollection(id: "harbor", title: "Saltwater Tapes", blurb: "Slower, with the tide underneath.", gate: .arrival(.harbor)),
        MusicCollection(id: "blossom", title: "Lantern Nights", blurb: "Evening music, music box forward.", gate: .arrival(.blossom)),
        MusicCollection(id: "chill2", title: "Paws & Chill II", blurb: "Five more of the same warmth.", gate: .plus),
        MusicCollection(id: "cloudspire", title: "Cloudspire Drift", blurb: "Airy and sparse, mostly pads.", gate: .plus),
        MusicCollection(id: "nighttrain", title: "Night Train", blurb: "Rail rhythm at half speed.", gate: .plus),
        MusicCollection(id: "onsen", title: "Moonlit Onsen", blurb: "Mallets and plucks over water.", gate: .plus),
        MusicCollection(id: "starfall", title: "Starfall", blurb: "The sparsest set. Space between notes.", gate: .plus),
        MusicCollection(id: "rainyday", title: "Rainy Day Tapes", blurb: "Written to leave room for the rain.", gate: .found(.rainyday)),
        MusicCollection(id: "nightshift", title: "Night Shift", blurb: "For the hours nobody else is up for.", gate: .found(.nightshift)),
        MusicCollection(id: "soot", title: "Soot's Tape", blurb: "Five lullabies. Nobody knows where she got them.", gate: .found(.soot)),
    ]

    static let tracks: [MusicTrack] = [
        MusicTrack(id: "first_light", title: "First Light Loop", collection: "chill1", gate: .free, bpm: 70, energy: 2, loopFrames: 604800),
        MusicTrack(id: "homework_for_two", title: "Homework for Two", collection: "chill1", gate: .free, bpm: 72, energy: 2, loopFrames: 588000),
        MusicTrack(id: "corner_desk", title: "Corner Desk", collection: "chill1", gate: .free, bpm: 68, energy: 2, loopFrames: 622592),
        MusicTrack(id: "sleepy_metronome", title: "Sleepy Metronome", collection: "chill1", gate: .free, bpm: 66, energy: 1, loopFrames: 641456),
        MusicTrack(id: "warm_static", title: "Warm Static", collection: "chill1", gate: .free, bpm: 74, energy: 2, loopFrames: 572112),
        MusicTrack(id: "dew_on_the_fence", title: "Dew on the Fence", collection: "meadow", gate: .arrival(.meadow), bpm: 76, energy: 3, loopFrames: 557056),
        MusicTrack(id: "kettle_song", title: "Kettle Song", collection: "meadow", gate: .arrival(.meadow), bpm: 70, energy: 2, loopFrames: 604800),
        MusicTrack(id: "clover_rows", title: "Clover Rows", collection: "meadow", gate: .arrival(.meadow), bpm: 72, energy: 2, loopFrames: 588000),
        MusicTrack(id: "biscuits_nap", title: "Biscuit's Nap", collection: "meadow", gate: .arrival(.meadow), bpm: 64, energy: 1, loopFrames: 661504),
        MusicTrack(id: "chimney_smoke", title: "Chimney Smoke", collection: "meadow", gate: .arrival(.meadow), bpm: 68, energy: 1, loopFrames: 622592),
        MusicTrack(id: "needle_carpet", title: "Needle Carpet", collection: "woods", gate: .arrival(.woods), bpm: 66, energy: 1, loopFrames: 641456),
        MusicTrack(id: "creekside_study", title: "Creekside Study", collection: "woods", gate: .arrival(.woods), bpm: 70, energy: 2, loopFrames: 604800),
        MusicTrack(id: "mushroom_lamp", title: "Mushroom Lamp", collection: "woods", gate: .arrival(.woods), bpm: 62, energy: 1, loopFrames: 682840),
        MusicTrack(id: "old_log_bridge", title: "Old Log Bridge", collection: "woods", gate: .arrival(.woods), bpm: 72, energy: 2, loopFrames: 588000),
        MusicTrack(id: "fern_light", title: "Fern Light", collection: "woods", gate: .arrival(.woods), bpm: 68, energy: 1, loopFrames: 622592),
        MusicTrack(id: "slow_tide", title: "Slow Tide", collection: "harbor", gate: .arrival(.harbor), bpm: 63, energy: 1, loopFrames: 672000),
        MusicTrack(id: "rope_and_plank", title: "Rope & Plank", collection: "harbor", gate: .arrival(.harbor), bpm: 74, energy: 2, loopFrames: 572112),
        MusicTrack(id: "lighthouse_pulse", title: "Lighthouse Pulse", collection: "harbor", gate: .arrival(.harbor), bpm: 70, energy: 2, loopFrames: 604800),
        MusicTrack(id: "ferry_at_noon", title: "Ferry at Noon", collection: "harbor", gate: .arrival(.harbor), bpm: 72, energy: 2, loopFrames: 588000),
        MusicTrack(id: "salt_on_glass", title: "Salt on Glass", collection: "harbor", gate: .arrival(.harbor), bpm: 66, energy: 1, loopFrames: 641456),
        MusicTrack(id: "paper_glow", title: "Paper Glow", collection: "blossom", gate: .arrival(.blossom), bpm: 64, energy: 1, loopFrames: 661504),
        MusicTrack(id: "petal_drift", title: "Petal Drift", collection: "blossom", gate: .arrival(.blossom), bpm: 70, energy: 2, loopFrames: 604800),
        MusicTrack(id: "waterfall_ink", title: "Waterfall Ink", collection: "blossom", gate: .arrival(.blossom), bpm: 68, energy: 2, loopFrames: 622592),
        MusicTrack(id: "festival_ended", title: "Festival Ended", collection: "blossom", gate: .arrival(.blossom), bpm: 60, energy: 1, loopFrames: 705600),
        MusicTrack(id: "terrace_steps", title: "Terrace Steps", collection: "blossom", gate: .arrival(.blossom), bpm: 72, energy: 2, loopFrames: 588000),
        MusicTrack(id: "second_wind", title: "Second Wind", collection: "chill2", gate: .plus, bpm: 74, energy: 2, loopFrames: 572112),
        MusicTrack(id: "margin_notes", title: "Margin Notes", collection: "chill2", gate: .plus, bpm: 70, energy: 2, loopFrames: 604800),
        MusicTrack(id: "half_closed_eyes", title: "Half-Closed Eyes", collection: "chill2", gate: .plus, bpm: 64, energy: 1, loopFrames: 661504),
        MusicTrack(id: "borrowed_sweater", title: "Borrowed Sweater", collection: "chill2", gate: .plus, bpm: 68, energy: 1, loopFrames: 622592),
        MusicTrack(id: "sunday_loop", title: "Sunday Loop", collection: "chill2", gate: .plus, bpm: 72, energy: 2, loopFrames: 588000),
        MusicTrack(id: "above_the_weather", title: "Above the Weather", collection: "cloudspire", gate: .plus, bpm: 58, energy: 1, loopFrames: 729928),
        MusicTrack(id: "balloon_mail", title: "Balloon Mail", collection: "cloudspire", gate: .plus, bpm: 66, energy: 1, loopFrames: 641456),
        MusicTrack(id: "roots_in_the_sky", title: "Roots in the Sky", collection: "cloudspire", gate: .plus, bpm: 62, energy: 1, loopFrames: 682840),
        MusicTrack(id: "thin_air_waltz", title: "Thin Air Waltz", collection: "cloudspire", gate: .plus, bpm: 84, energy: 2, loopFrames: 756000),
        MusicTrack(id: "anchorless", title: "Anchorless", collection: "cloudspire", gate: .plus, bpm: 60, energy: 1, loopFrames: 705600),
        MusicTrack(id: "sleeper_car", title: "Sleeper Car", collection: "nighttrain", gate: .plus, bpm: 52, energy: 2, loopFrames: 814152),
        MusicTrack(id: "viaduct", title: "Viaduct", collection: "nighttrain", gate: .plus, bpm: 56, energy: 2, loopFrames: 756000),
        MusicTrack(id: "window_seat", title: "Window Seat", collection: "nighttrain", gate: .plus, bpm: 60, energy: 2, loopFrames: 705600),
        MusicTrack(id: "tunnel_counting", title: "Tunnel Counting", collection: "nighttrain", gate: .plus, bpm: 54, energy: 2, loopFrames: 784000),
        MusicTrack(id: "last_stop_lullaby", title: "Last Stop Lullaby", collection: "nighttrain", gate: .plus, bpm: 48, energy: 1, loopFrames: 882000),
        MusicTrack(id: "steam_rise", title: "Steam Rise", collection: "onsen", gate: .plus, bpm: 62, energy: 1, loopFrames: 682840),
        MusicTrack(id: "stone_and_water", title: "Stone & Water", collection: "onsen", gate: .plus, bpm: 66, energy: 2, loopFrames: 641456),
        MusicTrack(id: "capybara_club", title: "Capybara Club", collection: "onsen", gate: .plus, bpm: 70, energy: 2, loopFrames: 604800),
        MusicTrack(id: "warm_to_the_bone", title: "Warm to the Bone", collection: "onsen", gate: .plus, bpm: 58, energy: 1, loopFrames: 729928),
        MusicTrack(id: "snow_on_cedar", title: "Snow on Cedar", collection: "onsen", gate: .plus, bpm: 60, energy: 1, loopFrames: 705600),
        MusicTrack(id: "meteor_ledger", title: "Meteor Ledger", collection: "starfall", gate: .plus, bpm: 54, energy: 1, loopFrames: 784000),
        MusicTrack(id: "counting_in_the_dark", title: "Counting in the Dark", collection: "starfall", gate: .plus, bpm: 50, energy: 1, loopFrames: 846720),
        MusicTrack(id: "ridge_light", title: "Ridge Light", collection: "starfall", gate: .plus, bpm: 58, energy: 1, loopFrames: 729928),
        MusicTrack(id: "perseid_tape", title: "Perseid Tape", collection: "starfall", gate: .plus, bpm: 56, energy: 1, loopFrames: 756000),
        MusicTrack(id: "hello_moon", title: "Hello, Moon", collection: "starfall", gate: .plus, bpm: 46, energy: 1, loopFrames: 460172),
        MusicTrack(id: "windowpane_study", title: "Windowpane Study", collection: "rainyday", gate: .found(.rainyday), bpm: 66, energy: 1, loopFrames: 641456),
        MusicTrack(id: "gutter_song", title: "Gutter Song", collection: "rainyday", gate: .found(.rainyday), bpm: 62, energy: 1, loopFrames: 682840),
        MusicTrack(id: "second_umbrella", title: "Second Umbrella", collection: "rainyday", gate: .found(.rainyday), bpm: 70, energy: 2, loopFrames: 604800),
        MusicTrack(id: "wet_pavement", title: "Wet Pavement", collection: "rainyday", gate: .found(.rainyday), bpm: 64, energy: 1, loopFrames: 661504),
        MusicTrack(id: "nothing_urgent", title: "Nothing Urgent", collection: "rainyday", gate: .found(.rainyday), bpm: 68, energy: 2, loopFrames: 622592),
        MusicTrack(id: "third_coffee", title: "Third Coffee", collection: "nightshift", gate: .found(.nightshift), bpm: 64, energy: 1, loopFrames: 661504),
        MusicTrack(id: "the_building_is_empty", title: "The Building Is Empty", collection: "nightshift", gate: .found(.nightshift), bpm: 60, energy: 1, loopFrames: 705600),
        MusicTrack(id: "corridor_light", title: "Corridor Light", collection: "nightshift", gate: .found(.nightshift), bpm: 66, energy: 1, loopFrames: 641456),
        MusicTrack(id: "small_hours", title: "Small Hours", collection: "nightshift", gate: .found(.nightshift), bpm: 62, energy: 1, loopFrames: 682840),
        MusicTrack(id: "nobody_is_awake", title: "Nobody Is Awake", collection: "nightshift", gate: .found(.nightshift), bpm: 68, energy: 1, loopFrames: 622592),
        MusicTrack(id: "the_hedge", title: "The Hedge", collection: "soot", gate: .found(.soot), bpm: 56, energy: 1, loopFrames: 756000),
        MusicTrack(id: "fence_post", title: "Fence Post", collection: "soot", gate: .found(.soot), bpm: 60, energy: 1, loopFrames: 705600),
        MusicTrack(id: "six_feet_away", title: "Six Feet Away", collection: "soot", gate: .found(.soot), bpm: 54, energy: 1, loopFrames: 784000),
        MusicTrack(id: "she_stayed", title: "She Stayed", collection: "soot", gate: .found(.soot), bpm: 58, energy: 1, loopFrames: 729928),
        MusicTrack(id: "indoor_cat", title: "Indoor Cat", collection: "soot", gate: .found(.soot), bpm: 52, energy: 1, loopFrames: 814152),
    ]

    static func tracks(in collection: String) -> [MusicTrack] {
        tracks.filter { $0.collection == collection }
    }

    static func track(id: String) -> MusicTrack? {
        tracks.first { $0.id == id }
    }

    /// The one everybody starts with.
    static var opener: MusicTrack { tracks[0] }
}
